version: '3'

services:
  grafana-charting:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    user: ${USER_ID}
    volumes:
      - ~/volumes/grafana-data:/var/lib/grafana
      - ./grafana/json-data-stream:/var/lib/grafana/plugins/json-data-stream
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  user-db:
    container_name: user-db
    image: mysql:8.0.21
    ports:
      - 3306:3306
    volumes: 
      - ./user-settings:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
  main-server:
    build: ./
    image: artofimagination/main-server
    container_name: main-server
    ports:
      - 8080:8080
    depends_on: 
      - grafana-charting
      - user-db